"use client";
import type { NextPage } from "next";
import Head from "next/head";
import LocationCard from "../components/LocationCard";
import SystemInfoCard from "../components/SystemInfoCard";
import AccessCountCard from "../components/AccessCountCard";

const Home: NextPage = () => {
  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-100">
      <Head>
        <title>Info App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-4 sm:px-20 text-center">
        <div className="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:space-x-4">
          <LocationCard />
          <SystemInfoCard />
          <AccessCountCard />
        </div>
      </main>
    </div>
  );
};

export default Home;

